PACKAGE_NAME="cipher-kmod"
PACKAGE_VERSION="0.7.0"
MAKE[0]="make KDIR=/lib/modules/${kernelver}/build"
CLEAN="make clean KDIR=/lib/modules/${kernelver}/build"
BUILT_MODULE_NAME[0]="cipher_kmod"
DEST_MODULE_LOCATION[0]="/updates/dkms"
AUTOINSTALL="yes"
