// CP 5.3 STEP 2 side-build engine. Generated by gen_step2_engine.py from
// cipher_rt_phase4/cipher_rt_marlin_engine.cpp (the shipped, STEP-2-fixed
// engine). Adds a %smid 9th kernel arg + cipher_diag_quantize_export.
// NOT linked into libcipher_rt.so. The grid/guard fix logic is verbatim.
/* SPDX-License-Identifier: GPL-2.0-or-later
 *
 * cipher_rt_marlin_engine.cpp -- T4.5.2 Marlin INT4 GEMM engine.
 *
 * Distilled from cipher-may13-evidence/src/cipher_weight_compress.cpp
 * (Marlin-only subset). Provides:
 *   - NVRTC compile of cipher_rt_marlin_kernel_src_str → 10 kernel
 *     entry points (M=1..4, N=8|16, K=4|8, G=n1|8)
 *   - Per-weight lazy quantization (host-side fp16→INT4+scales)
 *   - Marlin XOR-swizzled repack (host-side using cipher_rt_marlin_perm
 *     and cipher_rt_marlin_scale_perm LUTs)
 *   - Marlin GEMM dispatch (grid=SM_count, block=256, dyn_shared=96K)
 *
 * The actuator (cipher_rt_marlin_actuator.c) calls into this engine via
 * the C-linkage functions at the bottom.
 *
 * Original Marlin: IST-DASLab (Apache-2.0).
 */
#define _GNU_SOURCE
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <cstdint>
#include <cmath>
#include <atomic>
#include <mutex>
#include <vector>
#include <unordered_map>

#include <dlfcn.h>

extern "C" {
#include "cipher_v2_internal.h"
#include "cipher_rt_marlin_kernel_src.h"
#include "cipher_rt_marlin.h"
}
#include "cipher_rt_marlin_perms.h"

/* CP 2.4 (2026-05-16) — cross-TU thread-local flag. PrimaryCtxGuard sets it
 * while Marlin's quant/repack path owns the calling thread; the CUPTI launch
 * callback (cipher_cupti.c) reads it and skips its per-launch green-context
 * enforcement for Marlin's OWN internal kernel launches — without that, the
 * callback re-greens the thread between our launches and the pin below would
 * not hold. See cp_2_4/MARLIN_HANG_ROOT_CAUSE.md. */
extern "C" { __thread int cipher_rt_in_marlin_quant = 0; }

/* CP 5.3 STEP 2 (2026-05-17) — green-context partition wiring. Returns the
 * verified SM count of this process's green context (8) when one is active,
 * else 0. Used to size the GEMM `grid` to the partition and to gate the
 * primary-context pin. Defined in cipher_rt_green_ctx.c; see STEP 2 scope
 * memo §3. */
extern "C" unsigned int cipher_rt_green_ctx_sm_count(void);

/* CP 5.3 STEP 2 item 4 (side-build only) — device buffer the
 * %smid-instrumented kernel writes per-block SM ids into. Set by the
 * STEP 2 harness before a dispatch; passed as the kernel's 9th arg.
 * The shipped engine has no such arg (8-arg kernel). */
extern "C" { void *cipher_diag_smid_buf = nullptr; }

/* ── NVRTC + CUDA driver function-pointer bindings (dlsym at init) ─────── */

namespace {

typedef int (*pf_nvrtcCreateProgram)(void**, const char*, const char*, int,
                                     const char* const*, const char* const*);
typedef int (*pf_nvrtcCompileProgram)(void*, int, const char* const*);
typedef int (*pf_nvrtcGetPTXSize)(void*, size_t*);
typedef int (*pf_nvrtcGetPTX)(void*, char*);
typedef int (*pf_nvrtcGetProgramLogSize)(void*, size_t*);
typedef int (*pf_nvrtcGetProgramLog)(void*, char*);
typedef int (*pf_nvrtcDestroyProgram)(void**);

typedef int (*pf_cuInit)(unsigned);
typedef int (*pf_cuModuleLoadData)(void**, const void*);
typedef int (*pf_cuModuleGetFunction)(void**, void*, const char*);
typedef int (*pf_cuLaunchKernel)(void*, unsigned, unsigned, unsigned,
                                 unsigned, unsigned, unsigned,
                                 unsigned, void*, void**, void**);
typedef int (*pf_cuFuncSetAttribute)(void*, int, int);
/* CUDA driver context API — CP 2.4 primary-context pin (see PrimaryCtxGuard). */
typedef int (*pf_cuCtxGetCurrent)(void**);
typedef int (*pf_cuCtxSetCurrent)(void*);
typedef int (*pf_cuDevicePrimaryCtxRetain)(void**, int);
/* CUDA runtime API for context bring-up + memcpy + malloc */
typedef int (*pf_cudaFree)(void*);
typedef int (*pf_cudaMalloc)(void**, size_t);
typedef int (*pf_cudaMemcpy)(void*, const void*, size_t, int);
typedef int (*pf_cudaMemcpyAsync)(void*, const void*, size_t, int, void*);
typedef int (*pf_cudaMemset)(void*, int, size_t);
typedef int (*pf_cudaMemsetAsync)(void*, int, size_t, void*);
typedef int (*pf_cudaDeviceGetAttribute)(int*, int, int);

struct Api {
    void *libnvrtc = nullptr;
    void *libcuda  = nullptr;
    void *libcudart= nullptr;

    pf_nvrtcCreateProgram     create_prog  = nullptr;
    pf_nvrtcCompileProgram    compile_prog = nullptr;
    pf_nvrtcGetPTXSize        get_ptx_size = nullptr;
    pf_nvrtcGetPTX            get_ptx      = nullptr;
    pf_nvrtcGetProgramLogSize get_log_size = nullptr;
    pf_nvrtcGetProgramLog     get_log      = nullptr;
    pf_nvrtcDestroyProgram    destroy_prog = nullptr;

    pf_cuInit                 cu_init        = nullptr;
    pf_cuModuleLoadData       module_load    = nullptr;
    pf_cuModuleGetFunction    module_getfn   = nullptr;
    pf_cuLaunchKernel         launch_kernel  = nullptr;
    pf_cuFuncSetAttribute     func_setattr   = nullptr;
    pf_cuCtxGetCurrent          ctx_get        = nullptr;
    pf_cuCtxSetCurrent          ctx_set        = nullptr;
    pf_cuDevicePrimaryCtxRetain primary_retain = nullptr;

    pf_cudaFree               rt_free        = nullptr;
    pf_cudaMalloc             rt_malloc      = nullptr;
    pf_cudaMemcpy             rt_memcpy      = nullptr;
    pf_cudaMemcpyAsync        rt_memcpy_async= nullptr;
    pf_cudaMemset             rt_memset      = nullptr;
    pf_cudaMemsetAsync        rt_memset_async= nullptr;
    pf_cudaDeviceGetAttribute rt_devattr     = nullptr;

    bool ok = false;
} g_api;
std::mutex g_api_mu;

bool resolve_api() {
    std::lock_guard<std::mutex> lk(g_api_mu);
    if (g_api.ok) return true;

    if (!g_api.libnvrtc) {
        g_api.libnvrtc = dlopen("libnvrtc.so.13", RTLD_LAZY | RTLD_LOCAL);
        if (!g_api.libnvrtc) g_api.libnvrtc = dlopen("libnvrtc.so.12", RTLD_LAZY | RTLD_LOCAL);
        if (!g_api.libnvrtc) g_api.libnvrtc = dlopen("libnvrtc.so",    RTLD_LAZY | RTLD_LOCAL);
    }
    if (!g_api.libcuda) {
        g_api.libcuda = dlopen("libcuda.so.1", RTLD_LAZY | RTLD_LOCAL);
    }
    if (!g_api.libcudart) {
        g_api.libcudart = dlopen("libcudart.so.13", RTLD_LAZY | RTLD_NOLOAD);
        if (!g_api.libcudart) g_api.libcudart = dlopen("libcudart.so.12", RTLD_LAZY | RTLD_NOLOAD);
        if (!g_api.libcudart) g_api.libcudart = dlopen("libcudart.so.13", RTLD_LAZY);
        if (!g_api.libcudart) g_api.libcudart = dlopen("libcudart.so.12", RTLD_LAZY);
        if (!g_api.libcudart) g_api.libcudart = dlopen("libcudart.so",    RTLD_LAZY);
    }
    if (!g_api.libnvrtc || !g_api.libcuda || !g_api.libcudart) {
        cipher_log("MARLIN: libnvrtc/libcuda/libcudart resolve failed "
                   "(nvrtc=%p cuda=%p cudart=%p)",
                   g_api.libnvrtc, g_api.libcuda, g_api.libcudart);
        return false;
    }

    g_api.create_prog  = (pf_nvrtcCreateProgram)dlsym(g_api.libnvrtc, "nvrtcCreateProgram");
    g_api.compile_prog = (pf_nvrtcCompileProgram)dlsym(g_api.libnvrtc, "nvrtcCompileProgram");
    g_api.get_ptx_size = (pf_nvrtcGetPTXSize)dlsym(g_api.libnvrtc, "nvrtcGetPTXSize");
    g_api.get_ptx      = (pf_nvrtcGetPTX)dlsym(g_api.libnvrtc, "nvrtcGetPTX");
    g_api.get_log_size = (pf_nvrtcGetProgramLogSize)dlsym(g_api.libnvrtc, "nvrtcGetProgramLogSize");
    g_api.get_log      = (pf_nvrtcGetProgramLog)dlsym(g_api.libnvrtc, "nvrtcGetProgramLog");
    g_api.destroy_prog = (pf_nvrtcDestroyProgram)dlsym(g_api.libnvrtc, "nvrtcDestroyProgram");

    g_api.cu_init       = (pf_cuInit)dlsym(g_api.libcuda, "cuInit");
    g_api.module_load   = (pf_cuModuleLoadData)dlsym(g_api.libcuda, "cuModuleLoadData");
    g_api.module_getfn  = (pf_cuModuleGetFunction)dlsym(g_api.libcuda, "cuModuleGetFunction");
    g_api.launch_kernel = (pf_cuLaunchKernel)dlsym(g_api.libcuda, "cuLaunchKernel");
    g_api.func_setattr  = (pf_cuFuncSetAttribute)dlsym(g_api.libcuda, "cuFuncSetAttribute");
    g_api.ctx_get       = (pf_cuCtxGetCurrent)dlsym(g_api.libcuda, "cuCtxGetCurrent");
    g_api.ctx_set       = (pf_cuCtxSetCurrent)dlsym(g_api.libcuda, "cuCtxSetCurrent");
    g_api.primary_retain= (pf_cuDevicePrimaryCtxRetain)dlsym(g_api.libcuda, "cuDevicePrimaryCtxRetain");

    g_api.rt_free        = (pf_cudaFree)dlsym(g_api.libcudart, "cudaFree");
    g_api.rt_malloc      = (pf_cudaMalloc)dlsym(g_api.libcudart, "cudaMalloc");
    g_api.rt_memcpy      = (pf_cudaMemcpy)dlsym(g_api.libcudart, "cudaMemcpy");
    g_api.rt_memcpy_async= (pf_cudaMemcpyAsync)dlsym(g_api.libcudart, "cudaMemcpyAsync");
    g_api.rt_memset      = (pf_cudaMemset)dlsym(g_api.libcudart, "cudaMemset");
    g_api.rt_memset_async= (pf_cudaMemsetAsync)dlsym(g_api.libcudart, "cudaMemsetAsync");
    g_api.rt_devattr     = (pf_cudaDeviceGetAttribute)dlsym(g_api.libcudart, "cudaDeviceGetAttribute");

    g_api.ok = g_api.create_prog && g_api.compile_prog
            && g_api.get_ptx_size && g_api.get_ptx
            && g_api.module_load && g_api.module_getfn
            && g_api.launch_kernel && g_api.func_setattr
            && g_api.rt_free && g_api.rt_malloc
            && g_api.rt_memcpy && g_api.rt_memcpy_async
            && g_api.rt_memset_async && g_api.rt_devattr;
    if (!g_api.ok) {
        cipher_log("MARLIN: API dlsym resolve incomplete");
    }
    return g_api.ok;
}

/* ── Marlin cubin table: 10 entry points, lazily looked up ─────────────── */

struct MarlinFn {
    int          m_blocks;
    int          n_blocks;
    int          k_blocks;
    int          group_blocks;  /* -1 (no groups) or 8 (group_size=128) */
    const char  *sym;
    void        *fn;            /* CUfunction handle, NULL until lookup */
};

MarlinFn g_marlin_fns[] = {
    {1,  8,  8, -1, "marlin_M1_N8_K8_Gn1",   nullptr},
    {1,  8,  8,  8, "marlin_M1_N8_K8_G8",    nullptr},
    {1, 16,  4, -1, "marlin_M1_N16_K4_Gn1",  nullptr},
    {1, 16,  4,  8, "marlin_M1_N16_K4_G8",   nullptr},
    {2, 16,  4, -1, "marlin_M2_N16_K4_Gn1",  nullptr},
    {2, 16,  4,  8, "marlin_M2_N16_K4_G8",   nullptr},
    {3, 16,  4, -1, "marlin_M3_N16_K4_Gn1",  nullptr},
    {3, 16,  4,  8, "marlin_M3_N16_K4_G8",   nullptr},
    {4, 16,  4, -1, "marlin_M4_N16_K4_Gn1",  nullptr},
    {4, 16,  4,  8, "marlin_M4_N16_K4_G8",   nullptr},
};
constexpr int N_MARLIN_FNS = sizeof(g_marlin_fns) / sizeof(g_marlin_fns[0]);

/* Forward decl — defined after ensure_marlin_compiled. */
void *nvrtc_compile_to_module(const char *src, const char *prog_name);

void *g_marlin_module = nullptr;
std::atomic<int> g_marlin_state{0};  /* 0=cold, 1=compiling, 2=ready, 3=failed */

/* T4.5.2 GPU quantize kernel — directly ported from
 * cipher-may13-evidence/src/cipher_weight_compress.cpp:198 (kQuantSrc).
 * Two passes: compute per-group fp16 scales; quantize + pack into nibbles.
 * Group size hard-coded at 128 (matches Marlin's expected layout).
 *
 * Also includes a transpose kernel: PyTorch stores W as (out, in) row-major,
 * but Marlin expects W in (K=in, N=out) row-major. cipher_w_transpose_fp16
 * does the transpose into a fresh device buffer before quant runs. */
static const char cipher_rt_quant_kernel_src_str[] = R"NVRTC(
#include <cuda_fp16.h>

#define CIPHER_QGROUP 128

extern "C" __global__ void cipher_w_transpose_fp16(
    const __half* __restrict__ in,    // (rows_in, cols_in) row-major
    __half*       __restrict__ out,   // (cols_in, rows_in) row-major
    int rows_in, int cols_in)
{
    int r = blockIdx.y * blockDim.y + threadIdx.y;  /* 0..rows_in-1 */
    int c = blockIdx.x * blockDim.x + threadIdx.x;  /* 0..cols_in-1 */
    if (r >= rows_in || c >= cols_in) return;
    /* out[c, r] = in[r, c] */
    out[(long long)c * rows_in + r] = in[(long long)r * cols_in + c];
}

extern "C" __global__ void cipher_w_compute_scales(
    const __half* __restrict__ in,
    __half*       __restrict__ out_scales,
    int rows, int cols)
{
    int g = blockIdx.x;
    int n = blockIdx.y * blockDim.x + threadIdx.x;
    if (n >= cols) return;
    int row_base = g * CIPHER_QGROUP;
    if (row_base >= rows) return;

    float a = 0.0f;
    int last = row_base + CIPHER_QGROUP;
    if (last > rows) last = rows;
    for (int k = row_base; k < last; ++k) {
        float v = __half2float(in[k * cols + n]);
        float av = v < 0.0f ? -v : v;
        if (av > a) a = av;
    }
    float scale = (a > 0.0f) ? (a / 7.0f) : 1.0f;
    out_scales[g * cols + n] = __float2half_rn(scale);
}

extern "C" __global__ void cipher_w_quant_pack(
    const __half* __restrict__ in,
    const __half* __restrict__ in_scales,
    unsigned char* __restrict__ out_int4,
    int rows, int cols)
{
    int k = blockIdx.y * blockDim.y + threadIdx.y;
    int c = blockIdx.x * blockDim.x + threadIdx.x;
    int half_cols = cols >> 1;
    if (k >= rows || c >= half_cols) return;

    int kg = k / CIPHER_QGROUP;
    int col0 = c << 1;
    int col1 = col0 + 1;

    float v0 = __half2float(in[k * cols + col0]);
    float v1 = __half2float(in[k * cols + col1]);
    float s0 = __half2float(in_scales[kg * cols + col0]);
    float s1 = __half2float(in_scales[kg * cols + col1]);

    int q0 = __float2int_rn(v0 / s0);
    int q1 = __float2int_rn(v1 / s1);
    if (q0 >  7) q0 =  7; if (q0 < -8) q0 = -8;
    if (q1 >  7) q1 =  7; if (q1 < -8) q1 = -8;
    unsigned char b = ((unsigned char)(q1 & 0xF) << 4)
                    | ((unsigned char)(q0 & 0xF));
    out_int4[k * half_cols + c] = b;
}
)NVRTC";

void *g_quant_module = nullptr;
void *g_quant_fn_scales = nullptr;
void *g_quant_fn_pack   = nullptr;
void *g_quant_fn_transpose = nullptr;
std::atomic<int> g_quant_state{0};  /* 0=cold, 1=compiling, 2=ready, 3=failed */

bool ensure_marlin_compiled() {
    int state = g_marlin_state.load(std::memory_order_acquire);
    if (state == 2) return true;
    if (state == 3) return false;

    /* Race: only first thread compiles. */
    int expected = 0;
    if (!g_marlin_state.compare_exchange_strong(expected, 1)) {
        /* Someone else is compiling — spin briefly. */
        while ((state = g_marlin_state.load(std::memory_order_acquire)) == 1) {
            struct timespec ts = {0, 1000000};  /* 1 ms */
            nanosleep(&ts, nullptr);
        }
        return state == 2;
    }

    if (!resolve_api()) { g_marlin_state.store(3); return false; }

    /* Force CUDA context creation (cudaFree(0) is the documented idiom). */
    if (g_api.rt_free) (void)g_api.rt_free(nullptr);

    cipher_log("MARLIN: NVRTC compile starting (kernel src %zu bytes, sm_90)...",
               strlen(cipher_rt_marlin_kernel_src_str));
    struct timespec t0, t1;
    clock_gettime(CLOCK_MONOTONIC, &t0);

    if (g_api.rt_free) (void)g_api.rt_free(nullptr);  /* CUDA ctx bring-up */
    g_marlin_module = nvrtc_compile_to_module(cipher_rt_marlin_kernel_src_str,
                                               "cipher_rt_marlin.cu");
    if (!g_marlin_module) { g_marlin_state.store(3); return false; }

    int found = 0;
    for (int i = 0; i < N_MARLIN_FNS; i++) {
        void *fn = nullptr;
        if (g_api.module_getfn(&fn, g_marlin_module, g_marlin_fns[i].sym) == 0 && fn) {
            g_marlin_fns[i].fn = fn;
            /* MAX_DYN_SHARED_SIZE = 96K (attr id 8). */
            (void)g_api.func_setattr(fn, 8, 96 * 1024);
            found++;
        } else {
            cipher_log("MARLIN: WARN missing entry '%s'", g_marlin_fns[i].sym);
        }
    }

    clock_gettime(CLOCK_MONOTONIC, &t1);
    double elapsed_s = (t1.tv_sec - t0.tv_sec) + (t1.tv_nsec - t0.tv_nsec) / 1e9;
    cipher_log("MARLIN: cubin ready (%d/%d entry points in %.2f s)",
               found, N_MARLIN_FNS, elapsed_s);

    if (found == 0) { g_marlin_state.store(3); return false; }
    g_marlin_state.store(2, std::memory_order_release);
    return true;
}

void *marlin_get_function(int m_blocks, int n_blocks, int k_blocks, int group_blocks) {
    for (int i = 0; i < N_MARLIN_FNS; i++) {
        if (g_marlin_fns[i].m_blocks == m_blocks &&
            g_marlin_fns[i].n_blocks == n_blocks &&
            g_marlin_fns[i].k_blocks == k_blocks &&
            g_marlin_fns[i].group_blocks == group_blocks)
            return g_marlin_fns[i].fn;
    }
    return nullptr;
}

/* Compile NVRTC source → module, returning module handle. NULL on failure.
 * Caller calls cuModuleGetFunction afterwards to look up entry points. */
void *nvrtc_compile_to_module(const char *src, const char *prog_name)
{
    if (!resolve_api()) return nullptr;

    void *prog = nullptr;
    if (g_api.create_prog(&prog, src, prog_name, 0, nullptr, nullptr) != 0 || !prog) {
        cipher_log("MARLIN: nvrtcCreateProgram(%s) failed", prog_name);
        return nullptr;
    }
    const char *opts[] = {
        "--gpu-architecture=sm_90",
        "-std=c++17",
        "-I/usr/include",
        "--use_fast_math",
        "-default-device",
        "--ptxas-options=-O3",
    };
    int rc = g_api.compile_prog(prog, 6, opts);
    if (rc != 0) {
        size_t logsz = 0;
        g_api.get_log_size(prog, &logsz);
        if (logsz > 0 && logsz < 32768) {
            char *buf = (char *)alloca(logsz + 1);
            g_api.get_log(prog, buf);
            buf[logsz] = 0;
            cipher_log("MARLIN: nvrtc compile %s FAILED rc=%d log:\n%s", prog_name, rc, buf);
        } else {
            cipher_log("MARLIN: nvrtc compile %s FAILED rc=%d", prog_name, rc);
        }
        g_api.destroy_prog(&prog);
        return nullptr;
    }
    size_t ptxsz = 0;
    if (g_api.get_ptx_size(prog, &ptxsz) != 0 || ptxsz == 0) {
        g_api.destroy_prog(&prog); return nullptr;
    }
    std::vector<char> ptx(ptxsz);
    if (g_api.get_ptx(prog, ptx.data()) != 0) {
        g_api.destroy_prog(&prog); return nullptr;
    }
    g_api.destroy_prog(&prog);

    void *mod = nullptr;
    if (g_api.module_load(&mod, ptx.data()) != 0 || !mod) {
        cipher_log("MARLIN: cuModuleLoadData(%s) failed", prog_name);
        return nullptr;
    }
    return mod;
}

bool ensure_quant_compiled()
{
    int state = g_quant_state.load(std::memory_order_acquire);
    if (state == 2) return true;
    if (state == 3) return false;

    int expected = 0;
    if (!g_quant_state.compare_exchange_strong(expected, 1)) {
        while ((state = g_quant_state.load(std::memory_order_acquire)) == 1) {
            struct timespec ts = {0, 1000000}; nanosleep(&ts, nullptr);
        }
        return state == 2;
    }

    if (!resolve_api()) { g_quant_state.store(3); return false; }
    if (g_api.rt_free) (void)g_api.rt_free(nullptr);  /* CUDA ctx bring-up */

    struct timespec t0, t1;
    clock_gettime(CLOCK_MONOTONIC, &t0);
    g_quant_module = nvrtc_compile_to_module(cipher_rt_quant_kernel_src_str,
                                              "cipher_rt_quant.cu");
    if (!g_quant_module) { g_quant_state.store(3); return false; }
    if (g_api.module_getfn(&g_quant_fn_scales, g_quant_module,
                            "cipher_w_compute_scales") != 0 || !g_quant_fn_scales) {
        cipher_log("MARLIN: missing cipher_w_compute_scales entry");
        g_quant_state.store(3); return false;
    }
    if (g_api.module_getfn(&g_quant_fn_pack, g_quant_module,
                            "cipher_w_quant_pack") != 0 || !g_quant_fn_pack) {
        cipher_log("MARLIN: missing cipher_w_quant_pack entry");
        g_quant_state.store(3); return false;
    }
    if (g_api.module_getfn(&g_quant_fn_transpose, g_quant_module,
                            "cipher_w_transpose_fp16") != 0 || !g_quant_fn_transpose) {
        cipher_log("MARLIN: missing cipher_w_transpose_fp16 entry");
        g_quant_state.store(3); return false;
    }
    clock_gettime(CLOCK_MONOTONIC, &t1);
    double s = (t1.tv_sec - t0.tv_sec) + (t1.tv_nsec - t0.tv_nsec) / 1e9;
    cipher_log("MARLIN: GPU quant kernels compiled in %.2f s", s);
    g_quant_state.store(2, std::memory_order_release);
    return true;
}

/* ── Per-weight cache: pointer-keyed Marlin'd buffers ──────────────────── */

struct WeightSlot {
    int     observation_count;
    int     ready;          /* 1 once quantized + repacked */
    int     K;              /* rows (in-features) */
    int     N;              /* cols (out-features) */
    int     G;              /* group size (128) */
    void   *marlin_B;       /* device pointer, INT32-packed */
    void   *marlin_S;       /* device pointer, fp16 scales */
};

std::mutex g_weight_mu;
std::unordered_map<const void *, WeightSlot> g_weights;

WeightSlot *find_or_create_slot_locked(const void *w) {
    auto it = g_weights.find(w);
    if (it != g_weights.end()) return &it->second;
    WeightSlot s = {};
    auto [ins, _] = g_weights.emplace(w, s);
    return &ins->second;
}

/* ── Quantization: fp16 weight → INT4 packed + fp16 per-group scales ──── */
/*
 * GPU-side via two NVRTC-compiled kernels (cipher_w_compute_scales,
 * cipher_w_quant_pack). Output stays device-side; we DtoH-copy for the
 * host-side Marlin repack which uses the 1024-entry LUT.
 *
 * Layout produced (matches the prior cipher_weight_compress quant output):
 *   int4_packed: K rows × N/2 bytes — two signed-4-bit values per byte
 *                (low nibble = even col, high nibble = odd col)
 *   scales:      K/G rows × N fp16 values — per-group absmax / 7
 * This is the input format expected by marlin_repack_host().
 */
bool quantize_fp16_to_int4_groupwise_gpu(
    const void *d_fp16_weight, int K, int N, int G,
    std::vector<uint8_t> *out_int4, std::vector<uint16_t> *out_scales_fp16)
{
    if ((K % G) != 0 || G != 128) return false;
    int KG = K / G;
    size_t pack_bytes = (size_t)K * (N / 2);
    size_t scale_cnt  = (size_t)KG * N;

    if (!ensure_quant_compiled()) return false;

    /* PyTorch's Linear weight is stored row-major as (out=N, in=K). Marlin
     * expects the weight in (K, N) row-major. Transpose first into a fresh
     * device buffer. (cuBLAS A operand IS PyTorch's W; we need its bytes
     * reinterpreted as (K, N).) */
    void *d_w_T = nullptr;
    if (g_api.rt_malloc(&d_w_T, (size_t)K * N * 2) != 0) return false;
    {
        int rows_in = N;  /* original (out, in) row-major has rows = out = N */
        int cols_in = K;  /* and cols = in = K */
        int bx = 32, by = 8;
        int gx = (cols_in + bx - 1) / bx;
        int gy = (rows_in + by - 1) / by;
        void *args[] = { (void *)&d_fp16_weight, &d_w_T, &rows_in, &cols_in };
        int rc = g_api.launch_kernel(g_quant_fn_transpose, gx, gy, 1, bx, by, 1,
                                     0, nullptr, args, nullptr);
        if (rc != 0) {
            cipher_log("MARLIN: transpose kernel launch rc=%d", rc);
            g_api.rt_free(d_w_T); return false;
        }
    }

    /* Allocate device buffers for int4 + scales. */
    void *d_int4 = nullptr;
    void *d_scl  = nullptr;
    if (g_api.rt_malloc(&d_int4, pack_bytes) != 0) {
        g_api.rt_free(d_w_T); return false;
    }
    if (g_api.rt_malloc(&d_scl, scale_cnt * 2 /* fp16 */) != 0) {
        g_api.rt_free(d_w_T); g_api.rt_free(d_int4); return false;
    }

    /* Pass 1: compute per-group scales (groups along K = rows of d_w_T). */
    {
        int bx = 128;
        int gx = KG;
        int gy = (N + bx - 1) / bx;
        void *args[] = { &d_w_T, &d_scl, &K, &N };
        int rc = g_api.launch_kernel(g_quant_fn_scales, gx, gy, 1, bx, 1, 1,
                                     0, nullptr, args, nullptr);
        if (rc != 0) {
            cipher_log("MARLIN: scales kernel launch rc=%d", rc);
            g_api.rt_free(d_w_T); g_api.rt_free(d_int4); g_api.rt_free(d_scl);
            return false;
        }
    }
    /* Pass 2: quantize + pack each byte. */
    {
        int bx = 32, by = 8;
        int half_N = N / 2;
        int gx = (half_N + bx - 1) / bx;
        int gy = (K + by - 1) / by;
        void *args[] = { &d_w_T, &d_scl, &d_int4, &K, &N };
        int rc = g_api.launch_kernel(g_quant_fn_pack, gx, gy, 1, bx, by, 1,
                                     0, nullptr, args, nullptr);
        if (rc != 0) {
            cipher_log("MARLIN: pack kernel launch rc=%d", rc);
            g_api.rt_free(d_w_T); g_api.rt_free(d_int4); g_api.rt_free(d_scl);
            return false;
        }
    }

    /* DtoH for the host-side Marlin repack. */
    out_int4->resize(pack_bytes);
    out_scales_fp16->resize(scale_cnt);
    if (g_api.rt_memcpy(out_int4->data(), d_int4, pack_bytes, /*DtoH*/ 2) != 0 ||
        g_api.rt_memcpy(out_scales_fp16->data(), d_scl, scale_cnt * 2, /*DtoH*/ 2) != 0) {
        g_api.rt_free(d_w_T); g_api.rt_free(d_int4); g_api.rt_free(d_scl);
        return false;
    }
    g_api.rt_free(d_w_T);
    g_api.rt_free(d_int4);
    g_api.rt_free(d_scl);
    return true;
}

/* ── Marlin repack: pack signed nibbles into Marlin XOR-swizzled int32 ──
 * Direct port from cipher-may13-evidence/src/cipher_weight_compress.cpp
 * lines 880-980, adapted to use cipher_rt_marlin_perm/_scale_perm. */
struct MarlinPacked { void *B; void *S; int K; int N; int G; };

bool marlin_repack_host(const uint8_t *h_int4, const uint16_t *h_scales,
                        int K, int N, int G, MarlinPacked *out)
{
    if ((K % 16) != 0 || (N % 64) != 0 || G != 128) return false;
    int KG = K / G;
    int K_tiles = K / 16;
    int N_tiles = N / 16;

    /* 1. Unpack signed nibbles → unsigned [0,15] (signed_val + 8 mod 16). */
    std::vector<uint8_t> w((size_t)K * N);
    for (int k = 0; k < K; ++k) {
        for (int c = 0; c < N / 2; ++c) {
            uint8_t b = h_int4[(size_t)k * (N / 2) + c];
            int low  = b & 0xF;
            int high = (b >> 4) & 0xF;
            /* Sign-extend the signed nibble before adding 8 (the actual
             * Marlin convention treats nibbles as unsigned-biased). */
            int slo = (low  & 0x8) ? (low  - 16) : low;
            int shi = (high & 0x8) ? (high - 16) : high;
            w[(size_t)k * N + 2 * c]     = (uint8_t)((slo + 8) & 0xF);
            w[(size_t)k * N + 2 * c + 1] = (uint8_t)((shi + 8) & 0xF);
        }
    }

    /* 2. Reshape (K/16, 16, N/16, 16) → permute (0,2,1,3) → flatten. */
    size_t row_size = (size_t)N * 16;
    std::vector<uint8_t> tiled((size_t)K_tiles * row_size);
    for (int kt = 0; kt < K_tiles; ++kt) {
        for (int nt = 0; nt < N_tiles; ++nt) {
            for (int ki = 0; ki < 16; ++ki) {
                for (int ni = 0; ni < 16; ++ni) {
                    tiled[(size_t)kt * row_size
                          + (size_t)nt * 256 + ki * 16 + ni]
                        = w[(size_t)(kt * 16 + ki) * N + (nt * 16 + ni)];
                }
            }
        }
    }

    /* 3. Apply cipher_rt_marlin_perm in 1024-chunks. */
    std::vector<uint8_t> permuted((size_t)K_tiles * row_size);
    int n_chunks = (int)(row_size / 1024);
    for (int r = 0; r < K_tiles; ++r) {
        for (int ch = 0; ch < n_chunks; ++ch) {
            const uint8_t *src = &tiled    [(size_t)r * row_size + ch * 1024];
                  uint8_t *dst = &permuted [(size_t)r * row_size + ch * 1024];
            for (int i = 0; i < 1024; ++i) dst[i] = src[cipher_rt_marlin_perm[i]];
        }
    }

    /* 4. Pack 8 4-bit values per int32; output (K/16, N*2) int32. */
    int packed_cols = N * 2;
    std::vector<uint32_t> marlin_B((size_t)K_tiles * packed_cols, 0);
    for (int r = 0; r < K_tiles; ++r) {
        for (int c = 0; c < packed_cols; ++c) {
            uint32_t q = 0;
            for (int i = 0; i < 8; ++i) {
                q |= ((uint32_t)permuted[(size_t)r * row_size + c * 8 + i]
                      & 0xF) << (4 * i);
            }
            marlin_B[(size_t)r * packed_cols + c] = q;
        }
    }

    /* 5. Scale permutation: per-group permute N columns in chunks of 64. */
    int n_scale_chunks = N / 64;
    std::vector<uint16_t> marlin_S_h((size_t)KG * N);
    for (int g = 0; g < KG; ++g) {
        for (int ch = 0; ch < n_scale_chunks; ++ch) {
            const uint16_t *src = &h_scales  [(size_t)g * N + ch * 64];
                  uint16_t *dst = &marlin_S_h[(size_t)g * N + ch * 64];
            for (int i = 0; i < 64; ++i) dst[i] = src[cipher_rt_marlin_scale_perm[i]];
        }
    }

    /* 6. HtoD push. */
    size_t marlin_B_bytes = (size_t)K_tiles * packed_cols * 4;
    size_t marlin_S_bytes = (size_t)KG * N * 2;
    if (g_api.rt_malloc(&out->B, marlin_B_bytes) != 0) return false;
    if (g_api.rt_malloc(&out->S, marlin_S_bytes) != 0) {
        g_api.rt_free(out->B); return false;
    }
    if (g_api.rt_memcpy(out->B, marlin_B.data(), marlin_B_bytes,
                        /*HtoD*/ 1) != 0) {
        g_api.rt_free(out->B); g_api.rt_free(out->S); return false;
    }
    if (g_api.rt_memcpy(out->S, marlin_S_h.data(), marlin_S_bytes,
                        /*HtoD*/ 1) != 0) {
        g_api.rt_free(out->B); g_api.rt_free(out->S); return false;
    }
    out->K = K; out->N = N; out->G = G;
    return true;
}

/* ── Marlin GEMM dispatch: parameter setup + launch ─────────────────────
 * Direct port from cipher-may13-evidence/src/cipher_weight_compress.cpp
 * lines 1312-1422 (the cipher_weight_compress_marlin_gemm function). */
int g_sm_count = 0;

/* ── Per-stream Marlin workspace registry (CP 2.4) ──────────────────────
 * The Marlin kernel uses a `locks` buffer as inter-CTA split-K semaphores.
 * Async kernels on different streams cannot share one buffer — they race.
 * The old op31 path serialized ALL Marlin GEMMs through one lock + one
 * shared stream (the CP 0.4/0.5 ~8.5 tok/s aggregate ceiling). Here each
 * caller stream gets a private MARLIN_WS_BYTES workspace, so N tenants on
 * N streams run N-way concurrently with no cross-stream sync — the GEMM
 * still launches on the caller's own stream.
 *
 * MARLIN_WS_SLOTS (256) >= any realistic concurrent-tenant count (the
 * CP 0.5 burst sweep peaks at N=192). With slots >= max-concurrent, the
 * LRU eviction victim is always a slot whose stream was destroyed (its
 * kernels long complete) — eviction never reassigns a live stream's
 * buffer, so it is race-free. >256 concurrent streams would need a
 * cuStreamDestroy callback; out of scope for the CP 2.4 gate. */
constexpr size_t MARLIN_WS_BYTES = (size_t)(32768 / 128) * 16 * sizeof(int);
constexpr int    MARLIN_WS_SLOTS = 256;

struct MarlinWsSlot {
    void    *stream;    /* key; nullptr = never-used slot */
    void    *ws;        /* device workspace, MARLIN_WS_BYTES; freed never */
    uint64_t last_use;  /* LRU tick */
};
MarlinWsSlot g_ws_slots[MARLIN_WS_SLOTS] = {};
std::mutex   g_ws_mu;
std::atomic<uint64_t> g_ws_tick{0};

/* Return a device `locks` workspace private to `stream`. NULL on failure.
 * Hit: O(slots) scan, sub-microsecond. Miss: lazy cudaMalloc of one slot. */
void *marlin_ws_for_stream(void *stream)
{
    uint64_t tick = g_ws_tick.fetch_add(1, std::memory_order_relaxed);
    std::lock_guard<std::mutex> lk(g_ws_mu);

    int free_idx = -1, lru_idx = 0;
    uint64_t lru_tick = UINT64_MAX;
    for (int i = 0; i < MARLIN_WS_SLOTS; i++) {
        if (g_ws_slots[i].ws && g_ws_slots[i].stream == stream) {
            g_ws_slots[i].last_use = tick;          /* hit */
            return g_ws_slots[i].ws;
        }
        if (!g_ws_slots[i].ws && free_idx < 0) free_idx = i;
        if (g_ws_slots[i].last_use < lru_tick) {
            lru_tick = g_ws_slots[i].last_use; lru_idx = i;
        }
    }
    /* miss: take a never-used slot, else evict the LRU slot's stream key
     * (its device buffer is reused — safe, see the invariant above). */
    int idx = (free_idx >= 0) ? free_idx : lru_idx;
    if (!g_ws_slots[idx].ws) {
        void *nb = nullptr;
        if (g_api.rt_malloc(&nb, MARLIN_WS_BYTES) != 0) return nullptr;
        (void)g_api.rt_memset(nb, 0, MARLIN_WS_BYTES);
        g_ws_slots[idx].ws = nb;
    }
    g_ws_slots[idx].stream   = stream;
    g_ws_slots[idx].last_use = tick;
    return g_ws_slots[idx].ws;
}

/* Diagnostic: how many distinct streams have a live workspace slot. */
int marlin_ws_live_slots(void)
{
    std::lock_guard<std::mutex> lk(g_ws_mu);
    int n = 0;
    for (int i = 0; i < MARLIN_WS_SLOTS; i++) if (g_ws_slots[i].ws) n++;
    return n;
}

bool marlin_gemm_launch(
    const void *a_fp16, const void *marlin_B, const void *marlin_S,
    void *c_fp16, int M, int N, int K, int G, void *stream)
{
    if (!a_fp16 || !marlin_B || !marlin_S || !c_fp16) return false;
    if (M <= 0 || M > 4*16) return false;
    if ((N & 63) != 0 || (K & 127) != 0) return false;
    if (G != 128 && G != -1) return false;
    if (!ensure_marlin_compiled()) return false;

    int thread_k, thread_n;
    if (M <= 16) { thread_k = 128; thread_n = 128; }
    else         { thread_k =  64; thread_n = 256; }
    if ((N % thread_n) != 0 || (K % thread_k) != 0) return false;

    int thread_n_blocks = thread_n / 16;
    int thread_k_blocks = thread_k / 16;
    int group_blocks    = (G == -1) ? -1 : (G / 16);

    int tot_m_blocks = (M + 15) / 16;
    if (tot_m_blocks > 4) return false;
    int m_blocks = tot_m_blocks;

    void *fn = marlin_get_function(m_blocks, thread_n_blocks, thread_k_blocks,
                                   group_blocks);
    if (!fn) {
        cipher_log("MARLIN: no kernel for M=%d m_blocks=%d n_blocks=%d k_blocks=%d g_blocks=%d",
                   M, m_blocks, thread_n_blocks, thread_k_blocks, group_blocks);
        return false;
    }

    if (g_sm_count == 0) g_api.rt_devattr(&g_sm_count, /*MultiProcessorCount*/16, 0);
    if (g_sm_count <= 0) g_sm_count = 132;

    /* Per-stream workspace (CP 2.4 registry — replaces the single shared
     * g_marlin_workspace that serialized all tenants in CP 0.4/0.5). */
    int max_par = 16;
    size_t ws_bytes = (size_t)(N / 128) * max_par * sizeof(int);
    if (ws_bytes > MARLIN_WS_BYTES) {
        cipher_log("MARLIN: N=%d exceeds per-stream workspace capacity", N);
        return false;
    }
    void *ws = marlin_ws_for_stream(stream);
    if (!ws) return false;
    /* Per-call clear of the prefix the kernel touches, on the launch stream.
     * The buffer is private to `stream`, so this is race-free. */
    g_api.rt_memset_async(ws, 0, ws_bytes, stream);

    int prob_m = M, prob_n = N, prob_k = K;
    int *locks = (int *)ws;
    void *args[] = { (void *)&a_fp16, (void *)&marlin_B, (void *)&c_fp16, (void *)&marlin_S,
                     &prob_m, &prob_n, &prob_k, &locks,
                     /* CP 5.3 STEP 2 item 4: 9th arg — %smid buffer. */
                     (void *)&cipher_diag_smid_buf };
    /* CP 5.3 STEP 2: when a green context is active, size the kernel `grid`
     * to the partition's verified SM count so the split-K CTAs are
     * co-resident inside the partition (STEP 1 proved the protocol is
     * grid-parametric down to grid=1). No green ctx → byte-identical to the
     * shipped single-tenant path. Scope memo §3 / §6 item 3. */
    unsigned int green_sm = cipher_rt_green_ctx_sm_count();
    int grid = (green_sm > 0) ? (int)green_sm : g_sm_count;
    int block = 256;
    int rc = g_api.launch_kernel(fn, grid, 1, 1, block, 1, 1,
                                 96 * 1024, stream, args, nullptr);
    if (rc != 0) {
        cipher_log("MARLIN: launch rc=%d (M=%d N=%d K=%d)", rc, M, N, K);
        return false;
    }
    return true;
}

/* ── CP 2.4 (2026-05-16): primary-context pin for the quant/repack path ──
 *
 * quantize_fp16_to_int4_groupwise_gpu mixes driver-API kernel launches on
 * the NULL stream (cuLaunchKernel) with runtime-API cudaMalloc / cudaMemcpy.
 * That sequence is only correct when the CURRENT CUDA context is the
 * runtime's primary context. The T4.2.4d green-context enforcement —
 * re-asserted by the CUPTI launch callback on EVERY cuLaunchKernel — makes a
 * green context current, so the quant kernels and the synchronous DtoH
 * cudaMemcpy land in the green context and the copy hangs. Latent since this
 * engine was written; exposed when kmod 0.4.8 let CUPTI subscribe. Full
 * diagnosis: cp_2_4/MARLIN_HANG_ROOT_CAUSE.md.
 *
 * PrimaryCtxGuard, held across the whole quant/repack sequence:
 *   - sets cipher_rt_in_marlin_quant=1 so the CUPTI callback skips
 *     green-enforcement for our own launches (else it re-greens the thread
 *     between them and the pin would not hold);
 *   - saves the caller's context, makes the device-0 primary context
 *     current — so malloc / launch / memcpy / free are all consistent;
 *   - restores both on destruction, covering every return path incl. errors. */
void          *g_primary_ctx = nullptr;
std::once_flag g_primary_once;

void *get_primary_ctx()
{
    std::call_once(g_primary_once, [] {
        if (g_api.primary_retain) {
            void *c = nullptr;
            if (g_api.primary_retain(&c, 0) == 0) g_primary_ctx = c;
        }
    });
    return g_primary_ctx;
}

struct PrimaryCtxGuard {
    void *saved  = nullptr;
    bool  ctx_ok = false;
    PrimaryCtxGuard()
    {
        cipher_rt_in_marlin_quant = 1;
        if (!g_api.ctx_get || !g_api.ctx_set) return;
        void *primary = get_primary_ctx();
        if (!primary) return;
        if (g_api.ctx_get(&saved) != 0)  return;
        if (g_api.ctx_set(primary) != 0) return;
        ctx_ok = true;
    }
    ~PrimaryCtxGuard()
    {
        if (ctx_ok) (void)g_api.ctx_set(saved);
        cipher_rt_in_marlin_quant = 0;
    }
    PrimaryCtxGuard(const PrimaryCtxGuard&) = delete;
    PrimaryCtxGuard &operator=(const PrimaryCtxGuard&) = delete;
};

/* Lazy quant+repack from the actuator hot path. Holds g_weight_mu while
 * doing the host-side work (one-shot per weight; subsequent calls hit
 * the cached path immediately). */
bool ensure_weight_quantized_repacked(const void *d_fp16_weight, int K, int N)
{
    {
        std::lock_guard<std::mutex> lk(g_weight_mu);
        WeightSlot *s = find_or_create_slot_locked(d_fp16_weight);
        if (s->ready) return true;
    }

    /* Do the host-side work outside the lock to avoid holding it during
     * the long HtoD/DtoH copies. */
    constexpr int G = 128;
    if ((K % G) != 0 || (N % 64) != 0 || (K % 16) != 0) return false;

    /* Pin the entire quant + repack GPU sequence to the primary context;
     * RAII-restored on every exit path below. See PrimaryCtxGuard above. */
    PrimaryCtxGuard ctx_guard;

    std::vector<uint8_t>  int4;
    std::vector<uint16_t> scales;
    if (!quantize_fp16_to_int4_groupwise_gpu(d_fp16_weight, K, N, G, &int4, &scales))
        return false;

    MarlinPacked m{};
    if (!marlin_repack_host(int4.data(), scales.data(), K, N, G, &m))
        return false;

    {
        std::lock_guard<std::mutex> lk(g_weight_mu);
        WeightSlot *s = find_or_create_slot_locked(d_fp16_weight);
        if (s->ready) {
            /* Another thread beat us; free our copy. */
            g_api.rt_free(m.B);
            g_api.rt_free(m.S);
            return true;
        }
        s->K = K; s->N = N; s->G = G;
        s->marlin_B = m.B;
        s->marlin_S = m.S;
        s->ready = 1;
    }
    return true;
}

} // anonymous namespace

/* ── Public engine API used by the actuator ──────────────────────────── */

extern "C" int cipher_rt_marlin_engine_init(void)
{
    if (!resolve_api()) return -1;
    /* Defer NVRTC compile to first eligible call (~19s cold; don't block
     * libcipher_rt init). */
    cipher_log("MARLIN: engine init OK (NVRTC + cuda + cudart resolved; "
               "cubin compile deferred to first eligible call)");
    return 0;
}

extern "C" int cipher_rt_marlin_engine_ensure_compiled(void)
{
    return ensure_marlin_compiled() ? 0 : -1;
}

extern "C" int cipher_rt_marlin_engine_observe_weight(const void *w_ptr)
{
    std::lock_guard<std::mutex> lk(g_weight_mu);
    WeightSlot *s = find_or_create_slot_locked(w_ptr);
    s->observation_count++;
    return s->observation_count;
}

extern "C" int cipher_rt_marlin_engine_is_ready(const void *w_ptr)
{
    std::lock_guard<std::mutex> lk(g_weight_mu);
    auto it = g_weights.find(w_ptr);
    if (it == g_weights.end()) return 0;
    return it->second.ready ? 1 : 0;
}

extern "C" int cipher_rt_marlin_engine_lookup(const void *w_ptr,
                                              void **out_B, void **out_S,
                                              int *out_K, int *out_N, int *out_G)
{
    std::lock_guard<std::mutex> lk(g_weight_mu);
    auto it = g_weights.find(w_ptr);
    if (it == g_weights.end() || !it->second.ready) return 0;
    WeightSlot &s = it->second;
    if (out_B) *out_B = s.marlin_B;
    if (out_S) *out_S = s.marlin_S;
    if (out_K) *out_K = s.K;
    if (out_N) *out_N = s.N;
    if (out_G) *out_G = s.G;
    return 1;
}

extern "C" int cipher_rt_marlin_engine_quantize_repack(
    const void *d_fp16_weight, int K, int N)
{
    if (!ensure_marlin_compiled()) return -1;
    return ensure_weight_quantized_repacked(d_fp16_weight, K, N) ? 0 : -1;
}

/* ── CP 5.3 STEP 1/2 diagnostic: quant export (side-build only) ─────────
 * Exposes the engine's exact GPU quant output (int4 packed + fp16 scales)
 * so the harness builds the cuBLAS reference from the SAME bytes Marlin
 * consumes. h_int4 holds K*(N/2) bytes; h_scales (K/128)*N uint16. */
extern "C" int cipher_diag_quantize_export(
    const void *d_fp16_weight, int K, int N,
    unsigned char *h_int4, unsigned short *h_scales)
{
    if (!ensure_marlin_compiled()) return -1;
    std::vector<uint8_t>  i4;
    std::vector<uint16_t> sc;
    if (!quantize_fp16_to_int4_groupwise_gpu(d_fp16_weight, K, N, 128, &i4, &sc))
        return -1;
    memcpy(h_int4,   i4.data(), i4.size());
    memcpy(h_scales, sc.data(), sc.size() * sizeof(uint16_t));
    return 0;
}

extern "C" int cipher_rt_marlin_engine_dispatch(
    const void *a_fp16, const void *marlin_B, const void *marlin_S,
    void *c_fp16, int M, int N, int K, int G, void *stream)
{
    /* CP 2.4 Fix A (2026-05-16): pin the GEMM dispatch to the primary
     * context, exactly as the quant path is pinned. The Marlin GEMM kernel
     * is structurally full-GPU — persistent-style, grid = SM count, with
     * inter-CTA split-K through the `locks` buffer; its CTAs must be
     * co-resident. Launched into a partitioned context (e.g. the 8-SM green
     * context) it deadlocks — confirmed by instrumentation, see
     * cp_2_4/MARLIN_HANG_ROOT_CAUSE.md. PrimaryCtxGuard makes the device-0
     * primary context current for the whole launch and restores the caller's
     * context on exit (RAII, every path). Single-tenant scope; multi-tenant
     * Marlin + SM-partitioning is a Phase 5 architectural problem — see
     * cp_2_4/PHASE_5_MARLIN_PARTITION_CONSTRAINT.md.
     *
     * CP 5.3 STEP 2 (2026-05-17): the primary-context pin is now scoped to
     * the single-tenant / no-partition path only. When a green context is
     * active the GEMM launches green-bound so its (partition-sized) grid is
     * confined to the partition — this is the deadlock fix CP 2.4 deferred
     * to Phase 5. Single-tenant path keeps the guard, byte-identical to the
     * shipped behaviour. Scope memo §3. */
    if (cipher_rt_green_ctx_sm_count() == 0) {
        PrimaryCtxGuard ctx_guard;
        return marlin_gemm_launch(a_fp16, marlin_B, marlin_S,
                                  c_fp16, M, N, K, G, stream) ? 0 : -1;
    }
    return marlin_gemm_launch(a_fp16, marlin_B, marlin_S,
                              c_fp16, M, N, K, G, stream) ? 0 : -1;
}

extern "C" unsigned long cipher_rt_marlin_engine_weights_count(void)
{
    std::lock_guard<std::mutex> lk(g_weight_mu);
    unsigned long n = 0;
    for (auto &kv : g_weights) if (kv.second.ready) n++;
    return n;
}

/* CP 2.4 diagnostic: distinct caller streams with a live workspace slot —
 * i.e. the per-stream concurrency width the Marlin path is sustaining. */
extern "C" int cipher_rt_marlin_engine_ws_slots(void)
{
    return marlin_ws_live_slots();
}
