#!/usr/bin/env python3
# CP 5.3 STEP 2 item 4 — generate the %smid-instrumented Marlin kernel source.
#
# Input : the SHIPPED kernel src (cipher_rt_phase4/cipher_rt_marlin_kernel_src.cpp)
# Output: cp53_marlin_kernel_src_step2.cpp — a side-build-only copy in which each
#         of the 10 `extern "C" __global__` wrapper entry points gains a trailing
#         `int* smids` parameter and a one-line %smid recorder prologue. The
#         templated `Marlin<...>` body is NOT touched. The shipped kernel src is
#         NOT modified (scope memo item 4: experimental side-build only).
#
# The recorder writes blockIdx.x's executing SM id once per block (thread 0).
# A block never migrates SMs during its lifetime, so recording at wrapper entry
# is the SM the block runs the GEMM on.
import sys

SRC = "/home/ubuntu/cipher_rt_phase4/cipher_rt_marlin_kernel_src.cpp"
DST = "/home/ubuntu/cipher-fusion-evidence/cp_5_3/cp53_marlin_kernel_src_step2.cpp"

txt = open(SRC).read()

# 1. wrapper signature: append `, int* smids` to all 10 entry points.
SIG_OLD = "    const int4* __restrict__ s, int prob_m, int prob_n, int prob_k, int* locks)"
SIG_NEW = "    const int4* __restrict__ s, int prob_m, int prob_n, int prob_k, int* locks, int* smids)"
n_sig = txt.count(SIG_OLD)
assert n_sig == 10, f"expected 10 wrapper signatures, found {n_sig}"
txt = txt.replace(SIG_OLD, SIG_NEW)

# 2. inject the recorder prologue into each wrapper body. After the signature
#    edit every wrapper opens `int* smids)\n{\n    Marlin<`.
BODY_OLD = "int* smids)\n{\n    Marlin<"
BODY_NEW = ("int* smids)\n{\n"
            "    CP53_RECORD_SMID(smids)\n"
            "    Marlin<")
n_body = txt.count(BODY_OLD)
assert n_body == 10, f"expected 10 wrapper bodies, found {n_body}"
txt = txt.replace(BODY_OLD, BODY_NEW)

# 3. define the recorder macro once, right after the cuda_fp16 include.
INC = "#include <cuda_fp16.h>\n"
assert txt.count(INC) == 1, "cuda_fp16 include not found exactly once"
MACRO = (INC +
         "\n// CP 5.3 STEP 2 item 4 — per-block %smid recorder (side-build only).\n"
         "#define CP53_RECORD_SMID(smids) do {                               \\\n"
         "  if (threadIdx.x == 0 && (smids) != 0) {                          \\\n"
         "    unsigned int _cp53_sm;                                         \\\n"
         "    asm volatile(\"mov.u32 %0, %%smid;\" : \"=r\"(_cp53_sm));           \\\n"
         "    (smids)[blockIdx.x] = (int)_cp53_sm;                           \\\n"
         "  } } while (0);\n")
txt = txt.replace(INC, MACRO)

# 4. retag the provenance header comment (line 1) so the side-build is obvious.
txt = txt.replace(
    "// Marlin INT4 GEMM kernel source for NVRTC ingestion.",
    "// Marlin INT4 GEMM kernel source for NVRTC ingestion.\n"
    "// CP 5.3 STEP 2 item 4: %smid-INSTRUMENTED side-build copy. Generated by\n"
    "// gen_instrumented_kernel.py from cipher_rt_phase4/cipher_rt_marlin_kernel_src.cpp.\n"
    "// NOT linked into libcipher_rt.so. The shipped kernel src is unmodified.",
    1)

open(DST, "w").write(txt)
print(f"wrote {DST}: {n_sig} signatures + {n_body} prologues instrumented")
