#!/usr/bin/env python3
# CP 5.3 STEP 2 item 4 — generate the side-build Marlin engine.
#
# Input : the SHIPPED, STEP-2-FIXED engine
#         (cipher_rt_phase4/cipher_rt_marlin_engine.cpp — already carries the
#          grid<-green-sm-count wiring and the scoped PrimaryCtxGuard).
# Output: cp53_marlin_engine_step2.cpp — a side-build-only copy adding:
#   (a) a `cipher_diag_smid_buf` device-pointer global, passed as the 9th
#       kernel argument so the %smid-instrumented kernel can record per-block
#       SM ids (gates B/C);
#   (b) `cipher_diag_quantize_export` — exposes the engine's exact int4+scales
#       so the harness builds its cuBLAS reference from the SAME bytes Marlin
#       consumes (carried unchanged from the STEP 1 diag engine).
#
# The grid wiring and guard-scoping logic is COPIED VERBATIM from the shipped
# engine — the side-build tests the literal shipped fix. The shipped engine is
# NOT modified.
SRC = "/home/ubuntu/cipher_rt_phase4/cipher_rt_marlin_engine.cpp"
DST = "/home/ubuntu/cipher-fusion-evidence/cp_5_3/cp53_marlin_engine_step2.cpp"

txt = open(SRC).read()

# ── (a) smid-buffer global, declared right after the STEP 2 extern decl ────
GREEN_EXT = "extern \"C\" unsigned int cipher_rt_green_ctx_sm_count(void);"
assert txt.count(GREEN_EXT) == 1
SMID_GLOBAL = (GREEN_EXT +
    "\n\n/* CP 5.3 STEP 2 item 4 (side-build only) — device buffer the\n"
    " * %smid-instrumented kernel writes per-block SM ids into. Set by the\n"
    " * STEP 2 harness before a dispatch; passed as the kernel's 9th arg.\n"
    " * The shipped engine has no such arg (8-arg kernel). */\n"
    "extern \"C\" { void *cipher_diag_smid_buf = nullptr; }")
txt = txt.replace(GREEN_EXT, SMID_GLOBAL)

# ── (a cont.) add the 9th kernel argument to the launch args[] ─────────────
ARGS_OLD = ("    void *args[] = { (void *)&a_fp16, (void *)&marlin_B, (void *)&c_fp16, (void *)&marlin_S,\n"
            "                     &prob_m, &prob_n, &prob_k, &locks };")
ARGS_NEW = ("    void *args[] = { (void *)&a_fp16, (void *)&marlin_B, (void *)&c_fp16, (void *)&marlin_S,\n"
            "                     &prob_m, &prob_n, &prob_k, &locks,\n"
            "                     /* CP 5.3 STEP 2 item 4: 9th arg — %smid buffer. */\n"
            "                     (void *)&cipher_diag_smid_buf };")
assert txt.count(ARGS_OLD) == 1, "launch args[] anchor not found"
txt = txt.replace(ARGS_OLD, ARGS_NEW)

# ── (b) cipher_diag_quantize_export, inserted before the dispatch entry ────
DISPATCH = "extern \"C\" int cipher_rt_marlin_engine_dispatch("
assert txt.count(DISPATCH) == 1
QEXPORT = (
    "/* ── CP 5.3 STEP 1/2 diagnostic: quant export (side-build only) ─────────\n"
    " * Exposes the engine's exact GPU quant output (int4 packed + fp16 scales)\n"
    " * so the harness builds the cuBLAS reference from the SAME bytes Marlin\n"
    " * consumes. h_int4 holds K*(N/2) bytes; h_scales (K/128)*N uint16. */\n"
    "extern \"C\" int cipher_diag_quantize_export(\n"
    "    const void *d_fp16_weight, int K, int N,\n"
    "    unsigned char *h_int4, unsigned short *h_scales)\n"
    "{\n"
    "    if (!ensure_marlin_compiled()) return -1;\n"
    "    std::vector<uint8_t>  i4;\n"
    "    std::vector<uint16_t> sc;\n"
    "    if (!quantize_fp16_to_int4_groupwise_gpu(d_fp16_weight, K, N, 128, &i4, &sc))\n"
    "        return -1;\n"
    "    memcpy(h_int4,   i4.data(), i4.size());\n"
    "    memcpy(h_scales, sc.data(), sc.size() * sizeof(uint16_t));\n"
    "    return 0;\n"
    "}\n\n")
txt = txt.replace(DISPATCH, QEXPORT + DISPATCH)

# ── retag provenance header ────────────────────────────────────────────────
HDR = txt.split("\n", 1)[0]
txt = ("// CP 5.3 STEP 2 side-build engine. Generated by gen_step2_engine.py from\n"
       "// cipher_rt_phase4/cipher_rt_marlin_engine.cpp (the shipped, STEP-2-fixed\n"
       "// engine). Adds a %smid 9th kernel arg + cipher_diag_quantize_export.\n"
       "// NOT linked into libcipher_rt.so. The grid/guard fix logic is verbatim.\n"
       + txt)

open(DST, "w").write(txt)
print(f"wrote {DST}")
