#!/usr/bin/env python3
"""
HyperFlux Weight Export Tool
Converts PyTorch INT8 quantized models (.pt) → C++ .inc weight arrays.

Usage:
    python export_weights.py --model path/to/model_int8.pt \
                             --kernel ballistics \
                             --output ../src/weights/hf_ballistics_w.inc

The .pt file must contain a state_dict with INT8 quantized weights
following HyperFlux QAT conventions:
    - 'layerN.weight' : INT8 tensor [out_dim, in_dim]
    - 'layerN.weight_scale' : FP32 tensor [out_dim] (per-channel)
    - 'layerN.bias' : FP32 tensor [out_dim]
    - 'layerN.input_scale' : FP32 scalar
    - 'layerN.input_zero_point' : FP32 scalar
"""

import argparse
import struct
import numpy as np

def load_model(path):
    try:
        import torch
        state = torch.load(path, map_location='cpu', weights_only=True)
        if isinstance(state, dict) and 'state_dict' in state:
            state = state['state_dict']
        return state
    except Exception as e:
        print(f"Error loading model: {e}")
        raise

# Obfuscation key (must match C++ hf_weight_loader.cpp)
OBF_KEY = bytes([
    0x4E, 0x44, 0x48, 0x46, 0x2D, 0x31, 0x2E, 0x30,
    0xA7, 0x3B, 0xC5, 0x19, 0xE2, 0x6F, 0x8D, 0x54,
    0x91, 0x0C, 0xF3, 0x7A, 0xB8, 0x25, 0xD6, 0x43,
    0x6E, 0x1D, 0xAF, 0x82, 0x59, 0xC0, 0x37, 0xE4
])

def obfuscate(data: bytes) -> bytes:
    result = bytearray(len(data))
    for i, b in enumerate(data):
        result[i] = b ^ OBF_KEY[i % len(OBF_KEY)]
    return bytes(result)

def fnv1a(data: bytes) -> int:
    h = 0x811C9DC5
    for b in data:
        h ^= b
        h = (h * 0x01000193) & 0xFFFFFFFF
    return h

def export_weights(model_path, kernel_name, output_path, obfuscate_weights=True):
    state = load_model(model_path)

    # Discover layers
    layer_keys = sorted(set(k.split('.')[0] for k in state.keys()
                           if k[0].isdigit() or k.startswith('layer')))

    # Normalize key format
    layers = []
    for i, lk in enumerate(layer_keys):
        w = state.get(f'{lk}.weight', state.get(f'{lk}.0.weight'))
        if w is None:
            continue

        w_np = w.numpy().astype(np.int8)
        out_dim, in_dim = w_np.shape
        in_dim_padded = (in_dim + 15) & ~15

        # Pad weights to aligned dimensions
        if in_dim_padded > in_dim:
            pad = np.zeros((out_dim, in_dim_padded - in_dim), dtype=np.int8)
            w_np = np.concatenate([w_np, pad], axis=1)

        scale = state.get(f'{lk}.weight_scale', state.get(f'{lk}.scale'))
        bias = state.get(f'{lk}.bias', None)
        iscale = state.get(f'{lk}.input_scale', None)
        izp = state.get(f'{lk}.input_zero_point', None)

        layers.append({
            'in_dim': in_dim,
            'out_dim': out_dim,
            'in_dim_padded': in_dim_padded,
            'weights': w_np.flatten(),
            'scales': scale.numpy().flatten() if scale is not None else np.ones(out_dim, dtype=np.float32) * 0.001,
            'biases': bias.numpy().flatten() if bias is not None else np.zeros(out_dim, dtype=np.float32),
            'input_scale': float(iscale) if iscale is not None else 1.0/127.0,
            'input_zero_point': float(izp) if izp is not None else 0.0,
        })

    if not layers:
        raise ValueError(f"No layers found in {model_path}")

    arch = ' -> '.join(str(layers[0]['in_dim']) if i == 0 else str(l['out_dim'])
                       for i, l in enumerate(layers))
    arch = str(layers[0]['in_dim']) + ' -> ' + ' -> '.join(str(l['out_dim']) for l in layers)

    # Generate .inc file
    lines = []
    lines.append(f'// HyperFlux SDK - {kernel_name.title()} Compiled Weights')
    lines.append(f'// Auto-generated by export_weights.py — DO NOT EDIT.')
    lines.append(f'// Architecture: {arch}')
    lines.append(f'// Layers: {len(layers)}')
    lines.append(f'//')
    lines.append(f'#include <cstdint>')
    lines.append(f'')
    lines.append(f'namespace hyperflux {{')
    lines.append(f'')

    # Input scales array
    lines.append(f'static const float s_{kernel_name}_iscale[{len(layers)}] = {{')
    lines.append(f'    ' + ', '.join(f'{l["input_scale"]:.8f}f' for l in layers))
    lines.append(f'}};')
    lines.append(f'static const float s_{kernel_name}_izp[{len(layers)}] = {{')
    lines.append(f'    ' + ', '.join(f'{l["input_zero_point"]:.8f}f' for l in layers))
    lines.append(f'}};')
    lines.append(f'')

    for i, l in enumerate(layers):
        w_bytes = l['weights'].tobytes()
        checksum = fnv1a(w_bytes)

        if obfuscate_weights:
            w_bytes = obfuscate(w_bytes)

        # Write INT8 weight array
        w_size = l['out_dim'] * l['in_dim_padded']
        lines.append(f'// Layer {i}: [{l["in_dim"]}({l["in_dim_padded"]})] -> [{l["out_dim"]}]  checksum=0x{checksum:08X}')
        lines.append(f'alignas(64) static const int8_t s_{kernel_name}_w{i}[{w_size}] = {{')

        # Format as hex rows of 32
        arr = list(w_bytes)
        for row_start in range(0, len(arr), 32):
            row = arr[row_start:row_start+32]
            hex_vals = ', '.join(f'0x{b:02X}' for b in row)
            comma = ',' if row_start + 32 < len(arr) else ''
            lines.append(f'    {hex_vals}{comma}')
        lines.append(f'}};')
        lines.append(f'')

        # Write scales
        lines.append(f'static const float s_{kernel_name}_s{i}[{l["out_dim"]}] = {{')
        scales_str = ', '.join(f'{v:.8f}f' for v in l['scales'])
        lines.append(f'    {scales_str}')
        lines.append(f'}};')

        # Write biases
        lines.append(f'static const float s_{kernel_name}_b{i}[{l["out_dim"]}] = {{')
        biases_str = ', '.join(f'{v:.8f}f' for v in l['biases'])
        lines.append(f'    {biases_str}')
        lines.append(f'}};')
        lines.append(f'')

    lines.append(f'}} // namespace hyperflux')

    with open(output_path, 'w') as f:
        f.write('\n'.join(lines))

    total_bytes = sum(l['out_dim'] * l['in_dim_padded'] for l in layers)
    print(f"Exported {kernel_name}: {len(layers)} layers, {total_bytes:,} weight bytes → {output_path}")

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Export HyperFlux weights to C++ .inc')
    parser.add_argument('--model', required=True, help='Path to INT8 .pt model')
    parser.add_argument('--kernel', required=True, help='Kernel name (e.g., ballistics)')
    parser.add_argument('--output', required=True, help='Output .inc file path')
    parser.add_argument('--no-obfuscate', action='store_true', help='Skip weight obfuscation')
    args = parser.parse_args()

    export_weights(args.model, args.kernel, args.output,
                   obfuscate_weights=not args.no_obfuscate)
